main: de.timesnake.basic.lounge.main.BasicLounge
version: ${version}
name: basic-lounge
author: timesnake
database: true
depend: [ basic-bukkit ]
api-version: 1.21

commands:
  startserver:
  startgame:
  teamselection: