main: de.timesnake.basic.lounge.main.BasicLounge
version: 1.3.1
name: basic-lounge
author: Mn
database: true
depend: [ basic-bukkit ]
api-version: 1.13

commands:
  startserver:
  startgame:
  teamselection: